language: cpp
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker-compose rm -f
  - docker-compose pull
  - docker-compose up --build -d

script:
  - docker exec dcore_container make test

after_script:
  - docker cp dcore_container:/home/testuser/opt/DCore/share/doc/dcore dcore_doc
  - docker-compose stop
  - docker-compose rm -f
  - find dcore_doc
