language: cpp
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker-compose rm -f
  - docker-compose pull
  - docker-compose up --build -d

script:
  - docker exec dcore_container make test

after_script:
  - docker cp -r dcore_container:build/DCore/doc/html .
  - docker-compose stop
  - docker-compose rm -f
  - find html
